<HTML><HEAD>
<TITLE>July 1994/Code Capsules/Listing 8</TITLE></HEAD>

<BODY BACKGROUND="" BGCOLOR="#FFFFFF" TEXT="#000000">

<h4><A NAME="heading1">Listing 8 <I>Deallocates a resource in the midst of handling an exception</A></I></h4>
<pre>// destroy4.cpp
#include &lt;stdio.h&gt;

void f(char *fname);

main()
{
   try
   {
      f("file1.dat");
   }
   catch(...)
   {
      puts("Exception caught in main()");
   }
   return 0;
}

void f(char *fname)
{
   FILE *fp = fopen(fname,"r");
   if (fp)
   {
      try
      {
         throw 1;
      }
      catch (...)
      {
         fclose(fp);
         puts("File closed");
         throw;  // Re-throw
      }
      
      fclose(fp); // The normal close
   }
}

/* Output:
File closed
Excepion caught in main()
*/

// End of File
</pre>
</BODY>
</HTML>
