



<HTML><HEAD>

<TITLE>December 1997/Error Handling with C++ Exceptions, Part 2/Listing 7</TITLE></HEAD>
<BODY BACKGROUND="" BGCOLOR="#FFFFFF" TEXT="#000000">
<h4>Listing 7:	Fixes the memory leak with auto_ptr</h4>

<pre>
// destroy9.cpp
#include &lt;stdio.h&gt;
#include &lt;memory&gt;       // For auto_ptr
    
using namespace std;

class File
{
    FILE* f;

public:
    File(const char* fname, const char* mode)
    {
        f = fopen(fname, mode);
        if (!f)
            throw 1;
    }
    ~File()
    {
        if (f)
        {
            fclose(f);
            puts("File closed");
        }
    }
};

main()
{
    void f(const char*);
    try
    {
        f("file1.dat");
    }
    catch(int x)
    {
        printf("Caught exception: %d\n",x);
    }
}

void f(const char* fname)
{
    auto_ptr&lt;File&gt; xp = new File(fname,"r");
    puts("Processing file...");
    throw 2;
}

// Output:
Processing file...
File closed
Caught exception: 2
//End of File
</pre>
</body></html>
